/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libsjf_JavaSjf */

#ifndef _Included_libsjf_JavaSjf
#define _Included_libsjf_JavaSjf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libsjf_JavaSjf
 * Method:    scheduleSJF
 * Signature: ([I[I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_libsjf_JavaSjf_scheduleSJF
  (JNIEnv *, jobject, jintArray, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
